# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c17b9c985d3372a15d305f77552b598659a938287766715808b89cd521dc3f782adf7f62a426e13c2d8aa61c4a0fc798ddf4c9cf18b525127ff7f833971019

test:
  secret_key_base: ccf7e44a5ffbca9aaf1c647a90abf5f01403342f1a6bab2b89b9c0417b693d9de43b47b64d0e79c133f19ba9b3a852b5445e1abb058a53182db37f702ec88b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
